/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'apex' at '17. 1. 3 오후 7:21' with Gradle 3.2.1
 *
 * @author apex, @date 17. 1. 3 오후 7:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
